import { useState } from 'react';
import { fetchRecipeImage, updateRecipeContent } from '../api/client';
import RecipeEditForm from './RecipeEditForm';

export default function RecipeDetail({ recipe: initialRecipe }) {
  const [recipe, setRecipe] = useState(initialRecipe);
  const [fetchingImage, setFetchingImage] = useState(false);
  const [editing, setEditing] = useState(false);
  const [editSaving, setEditSaving] = useState(false);

  const handleRefreshImage = async () => {
    setRecipe(r => ({ ...r, image_url: '' }));
    setFetchingImage(true);
    try {
      const result = await fetchRecipeImage(recipe.id);
      setRecipe(r => ({ ...r, image_url: result.image_url }));
    } catch (err) {
      console.error('Image fetch failed:', err);
    } finally {
      setFetchingImage(false);
    }
  };

  const handleEditSave = async ({ ingredients, instructions }) => {
    setEditSaving(true);
    try {
      await updateRecipeContent(recipe.id, ingredients, instructions);
      setRecipe(r => ({ ...r, ingredients, instructions }));
      setEditing(false);
    } catch (err) {
      alert('Failed to save: ' + err.message);
    } finally {
      setEditSaving(false);
    }
  };

  return (
    <div className="recipe-detail">
      <div className="recipe-detail-header">
        <h2>{recipe.title}</h2>
        {recipe.cuisine_type && <span className="cuisine-badge">{recipe.cuisine_type}</span>}
        <p className="recipe-description">{recipe.description}</p>
        <div className="recipe-meta">
          {recipe.prep_time_minutes > 0 && <span>{'\u23F1'} Prep: {recipe.prep_time_minutes} min</span>}
          {recipe.cook_time_minutes > 0 && <span>{'\uD83D\uDD25'} Cook: {recipe.cook_time_minutes} min</span>}
          <span>{'\uD83C\uDF7D'} Servings: {recipe.servings}</span>
          {recipe.difficulty && <span className={`difficulty difficulty-${recipe.difficulty}`}>{recipe.difficulty}</span>}
        </div>
      </div>

      {recipe.image_url && (
        <img className="recipe-detail-image" src={recipe.image_url} alt={recipe.title} />
      )}
      {recipe.id && (
        <div className="recipe-detail-image-action">
          <button className="btn btn-secondary btn-sm" onClick={handleRefreshImage} disabled={fetchingImage}>
            {fetchingImage ? 'Fetching…' : 'Refresh Image'}
          </button>
        </div>
      )}

      {recipe.dietary_restrictions && recipe.dietary_restrictions.length > 0 && (
        <div className="recipe-dietary">
          {recipe.dietary_restrictions.map(d => <span key={d} className="tag dietary-tag">{d}</span>)}
        </div>
      )}

      {editing ? (
        <RecipeEditForm
          recipe={recipe}
          onSave={handleEditSave}
          onCancel={() => setEditing(false)}
          saving={editSaving}
        />
      ) : (
        <>
          <div className="recipe-body">
            <section className="recipe-section recipe-ingredients">
              <div className="recipe-section-header">
                <h3>Ingredients</h3>
              </div>
              <ul className="ingredients-list">
                {recipe.ingredients && recipe.ingredients.map((ing, i) => (
                  <li key={i}>
                    <strong>{ing.amount} {ing.unit}</strong> {ing.name}
                    {ing.notes && <span className="ingredient-notes"> ({ing.notes})</span>}
                  </li>
                ))}
              </ul>
            </section>

            <section className="recipe-section recipe-instructions">
              <div className="recipe-section-header">
                <h3>Instructions</h3>
              </div>
              <ol className="instructions-list">
                {recipe.instructions && recipe.instructions.map((step, i) => (
                  <li key={i}>{step}</li>
                ))}
              </ol>
            </section>
          </div>

          {recipe.id && (
            <div className="recipe-edit-trigger">
              <button className="btn btn-secondary btn-sm" onClick={() => setEditing(true)}>
                Edit ingredients &amp; instructions
              </button>
            </div>
          )}
        </>
      )}

      {recipe.tags && recipe.tags.length > 0 && (
        <div className="recipe-tags">
          {recipe.tags.map(tag => <span key={tag} className="tag">{tag}</span>)}
        </div>
      )}

      {recipe.generated_by_model && (
        <p className="recipe-model">Generated by: {recipe.generated_by_model}</p>
      )}
    </div>
  );
}
